// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBqtf68DsOmEgwM0dqw9TZ_lEb6yAuRg1A',
    appId: '1:260836939385:web:a72cf0e8157bda9b8be6a8',
    messagingSenderId: '260836939385',
    projectId: 'shopping-list-collaborative',
    authDomain: 'shopping-list-collaborative.firebaseapp.com',
    storageBucket: 'shopping-list-collaborative.appspot.com',
    measurementId: 'G-TC4R46LTC1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC0-zlmDC9w7IllFgjMw7XXNm7xFoXt0BY',
    appId: '1:260836939385:android:85bda173b5075e888be6a8',
    messagingSenderId: '260836939385',
    projectId: 'shopping-list-collaborative',
    storageBucket: 'shopping-list-collaborative.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBoY0byJVNo2J3abxc60wF-hC7yYRrZRgE',
    appId: '1:260836939385:ios:47d3e8c389ef0f4f8be6a8',
    messagingSenderId: '260836939385',
    projectId: 'shopping-list-collaborative',
    storageBucket: 'shopping-list-collaborative.appspot.com',
    iosBundleId: 'com.example.shoppingListCollaborative',
  );
}
